In [65]:
import numpy as np
import pandas as pd

In [66]:
# View all rows and columns
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', None)

In [67]:
# Import the data
df = pd.read_csv('../../Data_Scraping/Data/Gurgaon/Independent_House/ind_house.csv') # Independent Houses data

In [68]:
df.sample(5)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
126,4 Bedroom House for sale in Nirvana Country,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,7 Crore,"₹ 23,333/sq.ft.",(223 sq.m.) Plot Area,Plot area 2400(222.97 sq.m.)Built Up area: 340...,4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,"Nirvana Country, Gurgaon, Haryana",3 Floors,North-East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",4 bhk villa sale in nirvana country \nGated \n...,"['5 Wardrobe', '1 Dining Table', '5 Light', '5...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5...",A68809650
413,12 Bedroom House for sale in Laxmi Garden,https://www.99acres.com/12-bhk-bedroom-indepen...,Laxmi Garden Sector-11,1.5 Crore,"₹ 12,820/sq.ft.",(109 sq.m.) Plot Area,Plot area 130(108.7 sq.m.),12 Bedrooms,9 Bathrooms,1 Balcony,"Pooja Room,Study Room,Servant Room,Others","House No 477/23, Laxmi Garden, Gurgaon, Haryana",3 Floors,East,1 to 5 Year Old,"['Hanuman Mandir', 'Sharma Hospital Gurgaon', ...",Property for sale. Area=130 sq yard; Front=30 ...,"['7 Wardrobe', '9 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'High Ceiling Height...","['Environment4 out of 5', 'Lifestyle4 out of 5...",S57354016
110,5 Bedroom House for sale in Sector 111 Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Puri Diplomatic Greens4.0 ★,NaN,"₹ 12,828/sq.ft.",(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN,V69909776
251,5 Bedroom House for sale in Vishnu Garden,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,1.35 Crore,"₹ 3,857/sq.ft.",(325 sq.m.) Built-up Area,Built Up area: 3500 (325.16 sq.m.)Carpet area:...,5 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Vishnu Garden, Sector 105, Vishnu Garden, Gurg...",3 Floors,East,undefined,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Solar power for 3kwh, 3 independent flora are ...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5...",Y69750790
158,4 Bedroom House for sale in Nirvana Country,https://www.99acres.com/4-bhk-bedroom-independ...,Unitech Deerwood Chase,15 Crore,"₹ 33,333/sq.ft.",(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,Servant Room,"Jf 67, Nirvana Country, Gurgaon, Haryana",2 Floors,West,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Raheja Mall', ...",A magnificent lifestyle curated for just the e...,"['6 Fan', '7 Light', 'No AC', 'No Bed', 'No Ch...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69448868

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1037 entries, 0 to 1036
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1037 non-null   object
 1   link             1037 non-null   object
 2   society          453 non-null    object
 3   price            968 non-null    object
 4   rate             999 non-null    object
 5   area             1037 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 170.3+ KB

In [70]:
# Check for duplicates
df.duplicated().sum()

13

In [71]:
df.drop_duplicates(inplace=True)

In [72]:
# Check for missing values
df.isnull().sum()

property_name       0
link                0
society           579
price              69
rate               38
                 ...
description         1
furnishDetails    292
features          362
rating            130
property_id         1
Length: 21, dtype: int64

In [73]:
# Columns to drop: Link, 
df.drop(columns=['link', 'property_id'], inplace=True)

In [74]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [75]:
# Renaming the columns
df.rename(columns={'rate': 'price_per_sqft'}, inplace=True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

# Univariate Analysis

In [76]:
# Society
df['society'].value_counts()

International City by SOBHA Phase 2    26
Emaar MGF Marbella                     26
Vipul Tatvam Villa                     24
International City by Sobha Phase 1    23
Unitech Uniworld Resorts               13
                                       ..
Jacobpura                               1
Indiabulls Centrum Park3.7 ★            1
Madan puri                              1
Signature Global Park4.0 ★              1
ROW HOUSE                               1
Name: society, Length: 185, dtype: int64

In [77]:
df['society'].isnull().sum()

579

In [78]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', "", str(name)).strip()).str.lower()

In [79]:
df['society'] = df['society'].str.replace('nan', 'independent')

In [80]:
df['society'].value_counts().shape  # Checking number of unique socities

(183,)

In [81]:
df['society'].value_counts()

independent                            579
emaar mgf marbella                      26
international city by sobha phase 2     26
vipul tatvam villa                      24
international city by sobha phase 1     23
                                      ...
huda flats                               1
jacobpura                                1
indiabulls centrum park                  1
madan puri                               1
huda plot sector 38                      1
Name: society, Length: 183, dtype: int64

In [82]:
# Price
df['price'].value_counts()

3.5 Crore     19
5.5 Crore     17
6.5 Crore     16
6 Crore       14
5 Crore       13
              ..
8.8 Crore      1
1.34 Crore     1
46 Lac         1
2.6 Crore      1
2.98 Crore     1
Name: price, Length: 302, dtype: int64

In [83]:
df['price'].isnull().sum()

69

In [84]:
df[df['price'] == 'Price on Request'].shape

(10, 19)

In [85]:
df = df[df['price'] != 'Price on Request']

In [86]:
# Create a function to convert all prices in same unit

def normalize_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100, 2)
        else:
            return round(float(x[0]), 2)

In [87]:
df['price'] = df['price'].str.split(' ').apply(normalize_price)

In [88]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [89]:
# price per sqft
df['price_per_sqft'].value_counts()

₹ 22,222/sq.ft.    14
₹ 11,111/sq.ft.    11
₹ 33,333/sq.ft.    11
₹ 10,000/sq.ft.    10
₹ 26,667/sq.ft.     6
                   ..
₹ 151/sq.ft.        1
₹ 25,103/sq.ft.     1
₹ 14,954/sq.ft.     1
₹ 8,784/sq.ft.      1
₹ 33,129/sq.ft.     1
Name: price_per_sqft, Length: 751, dtype: int64

In [90]:
# get only price per sqft
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹', '').str.replace(',','').str.strip().astype('float')

In [91]:
df.sample(5)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
519,3 Bedroom House for sale in Bhondsi,independent,0.44,4251.0,(96 sq.m.) Carpet Area,Carpet area: 115 (96.15 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,"Pooja Room,Others","Bhondsi, Gurgaon, Haryana",1 Floors,NaN,1 to 5 Year Old,NaN,This spacious 3 bhk independent house is avail...,NaN,"['Water Storage', 'Recently Renovated', 'Visit...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
243,7 Bedroom House for sale in Rajendra Park,independent,1.20,13333.0,(84 sq.m.) Plot Area,Plot area 900(83.61 sq.m.),7 Bedrooms,4 Bathrooms,1 Balcony,Others,"Rajendra Park, Gurgaon, Haryana",2 Floors,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Chintapurni Man...",12x12 and 13x12 rooms 2.5 floor buildup area t...,"['1 Geyser', '17 Light', '3 Wardrobe', 'No AC'...","['Water Storage', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1022,5 Bedroom House for sale in Sector 46 Gurgaon,independent,4.25,23148.0,(171 sq.m.) Plot Area,Plot area 204(170.57 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,Store Room,"Sector 46 Gurgaon, Gurgaon, Haryana",3 Floors,North-East,5 to 10 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",204 square yard built up property available fo...,"['4 Wardrobe', '10 Fan', '1 Exhaust Fan', '50 ...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Safety4 out of 5', ..."
62,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
456,4 Bedroom House for sale in DLF Phase 3,dlf city plots phase 3,1.44,26667.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),4 Bedrooms,2 Bathrooms,2 Balconies,NaN,"S Block, DLF Phase 3, Gurgaon, Haryana",1 Floors,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...","60 yard plot , s block , all aminities near bu...",[],['Park'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [92]:
# bedrooms
df['bedRoom'].value_counts()

4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
              ...
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: bedRoom, Length: 21, dtype: int64

In [93]:
df = df[~df['bedRoom'].isnull()]

In [94]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [95]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [96]:
df.sample(5)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
735,4 Bedroom House for sale in Palam Vihar,independent,2.95,15989.0,(171 sq.m.) Plot Area,Plot area 205(171.41 sq.m.),4,4 Bathrooms,3+ Balconies,NaN,"Palam Vihar, Gurgaon, Haryana",2 Floors,North-West,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",205 sq yard corner property available for sale...,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '10 L...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
888,2 Bedroom House for sale in Sector 70A Gurgaon,bptp pedestal,0.92,7750.0,(110 sq.m.) Carpet Area,Carpet area: 1187 (110.28 sq.m.),2,3 Bathrooms,3+ Balconies,Others,"123, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Ninex Mall', 'Airia Mall', 'Meditree Market'...",Wishing to settle down in an individual house ...,"['3 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Safety4 out of 5', ..."
20,9 Bedroom House for sale in Sector 9 Gurgaon,independent,3.40,12938.0,(244 sq.m.) Plot Area,Plot area 292(244.15 sq.m.),9,9 Bathrooms,3 Balconies,NaN,"Sector 9 Gurgaon, Gurgaon, Haryana",3 Floors,West,5 to 10 Year Old,"['State bank ATM', 'Esic Hospital Gurugram', '...",292 square yards triple story made 9 bhk house...,"['9 Wardrobe', '12 Fan', '1 Exhaust Fan', '50 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
970,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,5.50,21219.0,(241 sq.m.) Plot Area,Plot area 288(240.8 sq.m.),3,6 Bathrooms,2 Balconies,"Servant Room,Others","Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Vipul tatvam luxury 3bhk duplex villa \nSemi f...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Safety4 out of 5', ..."
177,4 Bedroom House for sale in Sector 56 Gurgaon,independent,4.00,26613.0,(140 sq.m.) Plot Area,Plot area 167(139.63 sq.m.),4,4 Bathrooms,3+ Balconies,NaN,"Sector 56 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,1 to 5 Year Old,"['Sector metro station', 'Sector metro station...","Two storey property adjacent to park , close p...","['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '2 Ge...","['Private Garden / Terrace', 'Water Storage', ...","['Environment4 out of 5', 'Lifestyle5 out of 5..."

In [97]:
# bathroom
df['bathroom'].value_counts()

4 Bathrooms     228
3 Bathrooms     165
5 Bathrooms     137
2 Bathrooms     114
6 Bathrooms      82
               ...
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: bathroom, Length: 21, dtype: int64

In [98]:
df[df['bathroom'].isnull()]

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, noOfFloor, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [99]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [100]:
df.sample(5)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
694,11 Bedroom House for sale in Sushant Lok Phase 1,independent,2.25,7500.0,(51 sq.m.) Plot Area,Plot area 550(51.1 sq.m.)Built Up area: 3000 s...,11,11,3+ Balconies,Others,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Best for investors , monthly rental income is ...","['1 Water Purifier', '11 Fan', '1 Fridge', '1 ...","['Maintenance Staff', 'Water Storage', 'Park',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
150,6 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok plots,5.80,29974.0,(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),6,6,3 Balconies,"Servant Room,Others","Sushant Lok Phase 1, Gurgaon, Haryana",2 Floors,South-West,1 to 5 Year Old,"['Huda city centre metro station', 'Sector 42-...",Available for sell 6bhk independent house vill...,"['6 Wardrobe', '5 Fan', '1 Exhaust Fan', '5 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
961,4 Bedroom House for sale in Uppals Southend,uppal southend,6.75,32328.0,(194 sq.m.) Built-up Area,Built Up area: 232 (193.98 sq.m.),4,4,3 Balconies,Servant Room,"Uppals Southend, Gurgaon, Haryana",3 Floors,West,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Uppal southend sector 49.Gated society plot si...,"['12 Wardrobe', '20 Fan', '1 Exhaust Fan', '12...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment5 out of 5', 'Safety5 out of 5', ..."
195,4 Bedroom House for sale in Maruti Kunj,independent,0.70,4117.0,(158 sq.m.) Plot Area,Plot area 1700(157.94 sq.m.),4,4,1 Balcony,NaN,"Maruti Kunj, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,Interested to sell independent house/villa.It ...,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
13,5 Bedroom House for sale in DLF Phase 1,independent,15.00,33200.0,(420 sq.m.) Plot Area,Plot area 502(419.74 sq.m.),5,6,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","A Block, DLF Phase 1, Gurgaon, Haryana",3 Floors,North,5 to 10 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",Genuine livable kothi at the rate of plot only...,"['5 Wardrobe', '9 Fan', '1 Exhaust Fan', '6 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [101]:
# balcony
df['balcony'].value_counts()

3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: balcony, dtype: int64

In [102]:
df['balcony'].isnull().sum()

0

In [103]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No', '0')

In [104]:
# additional Room
df['additionalRoom'].value_counts()

Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
                                                 ..
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: additionalRoom, Length: 56, dtype: int64

In [105]:
df['additionalRoom'].value_counts().shape

(56,)

In [106]:
df['additionalRoom'].isnull().sum()

386

In [107]:
df['additionalRoom'].fillna('not available', inplace=True)

In [108]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [109]:
df.sample(5)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
29,5 Bedroom House for sale in Nirvana Country,independent,10.56,32593.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),5,5,3,servant room,"Nirvana Country, Gurgaon, Haryana",3 Floors,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Urgent for sale\nOn main wide road\nConfirm de...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
80,4 Bedroom House for sale in Sector 23 Gurgaon,independent,5.00,16244.0,(286 sq.m.) Plot Area,Plot area 342(285.96 sq.m.),4,4,2,not available,"Sector 23 Gurgaon, Gurgaon, Haryana",2 Floors,East,10+ Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",Wishing to settle down in an individual house ...,"['4 Wardrobe', '6 Fan', '10 Light', '1 Modular...",['Water Storage'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."
715,3 Bedroom House for sale in Sector 23A Gurgaon,independent,5.10,16569.0,(286 sq.m.) Plot Area,Plot area 342(285.96 sq.m.)Built Up area: 125 ...,3,2,0,others,"Sector 23A Gurgaon, Gurgaon, Haryana",1 Floors,East,10+ Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",342 sq yards size of 2bhk with servant room av...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Water Storag...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
890,5 Bedroom House for sale in A Block Sushant Lo...,independent,9.85,29638.0,(350 sq.m.) Plot Area,Plot area 418(349.5 sq.m.),5,5,2,"pooja room,study room,servant room","A Block Sushant Lok Phase 1, Gurgaon, Haryana",3 Floors,West,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...",Sushant lok a maple community gated line near ...,NaN,"['Maintenance Staff', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Safety3 out of 5', ..."
217,3 Bedroom House for sale in Ashok Vihar,independent,1.50,10288.0,(135 sq.m.) Plot Area,Plot area 162(135.45 sq.m.)Built Up area: 210 ...,3,3,0,not available,"800 Lane 8 Ashok Vihar Part 1, Ashok Vihar, Gu...",NaN,NaN,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Ground floor and partial first floor built up,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [110]:
# floor num
df.rename(columns={'noOfFloor': 'floorNum'}, inplace=True)

In [111]:
df.sample(5)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
197,4 Bedroom House for sale in Mohan Nagar,independent,1.30,8701.0,(139 sq.m.) Plot Area,Plot area 166(138.8 sq.m.),4,4,2,not available,"Mohan Nagar, Gurgaon, Haryana",1 Floors,East,10+ Year Old,"['Astha Hospital', 'Kamal Hospital and Materni...","This 4 bhk house for sale in mohan nagar, a we...",NaN,NaN,NaN
436,1 Bedroom House for sale in Laxman Vihar,not applicable,0.40,9259.0,(40 sq.m.) Plot Area,Plot area 432(40.13 sq.m.),1,1,1,not available,"Laxman Vihar, Gurgaon, Haryana",1 Floors,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Prat...",Looking for buyer to purchase our house/villa ...,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
185,2 Bedroom House for sale in Daulatabad,secter 16a daultabad faridabad house no 313,0.48,60000.0,(7 sq.m.) Plot Area,Plot area 80(7.43 sq.m.),2,2,0,not available,"313, Daulatabad, Gurgaon, Haryana",02 Floors,South-East,1 to 5 Year Old,"['R K Hospital Gurgaon', 'Bhardwaj Hospital', ...",Check out this 2 bhk house for sale in daulata...,NaN,"['Private Garden / Terrace', 'Water Storage']",NaN
922,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,6.00,9634.0,(579 sq.m.) Plot Area,Plot area 692(578.6 sq.m.),4,5,3,not available,"N/a, Sector 109 Gurgaon, Gurgaon, Haryana",2 Floors,North-East,5 to 10 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...",Property description: On the lookout for a spa...,[],"['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
248,2 Bedroom House for sale in Ashok Vihar Phase ...,independent,0.75,57692.0,(12 sq.m.) Built-up Area,Built Up area: 130 (12.08 sq.m.),2,2,0,not available,"Ashok Vihar Phase 3 Extension, Ashok Vihar Pha...",1 Floors,NaN,undefined,NaN,This spacious residential house has total 1 fl...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."

In [112]:
df['floorNum'].value_counts().shape

(20,)

In [113]:
df['floorNum'].isnull().sum()

19

In [114]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).str.replace('Ground', '0').str.replace('Basement', '-1').str.replace('Lower', '0').str.extract(r'(\d+)')

In [115]:
df.sample(5)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
863,3 Bedroom House for sale in Sector 49 Gurgaon,eros rosewood villas,2.80,15555.0,(142 sq.m.) Plot Area,Plot area 1530(142.14 sq.m.)Built Up area: 190...,3,3,3,pooja room,"A22, Sector 49 Gurgaon, Gurgaon, Haryana",2,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Standard charter...",3 bhk duplex villa for sale in rosewood city w...,"['3 Wardrobe', '4 Fan', '4 Light', '1 Chimney'...","['Private Garden / Terrace', 'High Ceiling Hei...","['Environment4 out of 5', 'Safety5 out of 5', ..."
424,3 Bedroom House for sale in Sector 103 Gurgaon,independent,2.25,6367.0,(328 sq.m.) Built-up Area,Built Up area: 3534 (328.32 sq.m.)Carpet area:...,3,5,3+,not available,"Sector 103, Sector 103 Gurgaon, Gurgaon, Haryana",10,South,undefined,NaN,3bhk penthouse for resale in sector 103 sector...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
909,16 Bedroom House for sale in DLF Phase 2,independent,16.00,59259.0,(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.)Built Up area: 325 ...,16,16,3+,"servant room,study room,pooja room,store room","Dlf Phase 2, DLF Phase 2, Gurgaon, Haryana",4,West,0 to 1 Year Old,"['Vodafone belvedere towers metro station', 'D...","Dlf phase 2 very prime location , this buildin...","['1 Water Purifier', '24 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."
239,3 Bedroom House for sale in Sector 109 Gurgaon,ats tourmaline,1.87,8697.0,(200 sq.m.) Built-up Area,Built Up area: 2150 (199.74 sq.m.),3,4,0,not available,"Sector 109, Sector 109 Gurgaon, Gurgaon, Haryana",12,NaN,undefined,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...",A residential house is available for sale. It ...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
249,6 Bedroom House for sale in Surat Nagar Phase 2,independent,0.30,60000.0,(5 sq.m.) Plot Area,Plot area 50(4.65 sq.m.),6,3,3,not available,"814, Surat Nagar Phase 2, Gurgaon, Haryana",3,South,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Dr. ...",Wishing to settle down in an individual house ...,[],NaN,NaN

In [116]:
# facing
df['facing'].isnull().sum()

303

In [117]:
df['facing'].fillna('NA', inplace=True)

In [118]:
df['facing'].value_counts()

NA            303
East          178
North-East    158
North         109
West           75
North-West     44
South-East     39
South          34
South-West     24
Name: facing, dtype: int64

In [119]:
df['area'] = round((df['price']*10000000/df['price_per_sqft']))

In [120]:
df.insert(loc=1, column='property_type', value='house')

In [121]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [122]:
df.shape

(964, 20)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 964 entries, 0 to 1036
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    object
 1   property_type    964 non-null    object
 2   society          964 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     964 non-null    object
 7   bedRoom          964 non-null    int32
 8   bathroom         964 non-null    int32
 9   balcony          964 non-null    object
 10  additionalRoom   964 non-null    object
 11  address          959 non-null    object
 12  floorNum         945 non-null    object
 13  facing           964 non-null    object
 14  agePossession    964 non-null    object
 15  nearbyLocations  848 non-null    object
 16  description      964 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         662 non-null    object
 19  rating           843 non-null    object
dtypes: float64(3), int32(2), object(15)
memory usage: 150.6+ KB

In [124]:
df.to_csv('../../Data_Scraping/Data/Gurgaon/Independent_House/ind_house_cleaned.csv', index=False)